name: Release and Publish
on:
  push:
    branches:
      - master
    paths-ignore:
      - VERSION
      - CHANGELOG.md

jobs:
  release_publish:
    name: Release and Publish
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: docker build --target build -t build .
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_PATH: ./apps/web/assets/node_modules
        run: docker run --env-file <(env) build npx semantic-release
      - name: Checkout again (maybe the VERSION has changed)
        uses: actions/checkout@v1
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: brunozrk/aws_sauron
          tags: latest


