name: Release
on:
  push:
    branches:
      - master
    paths-ignore:
      - VERSION
      - CHANGELOG.md

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: docker build --target build -t build .
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_PATH: ./apps/web/assets/node_modules
        run: docker run --env-file <(env) build npx semantic-release
